---
title: |
  Text-Based Nudges Promoting Rubella Antibody Testing and Vaccination:
  Evidence from Nationwide Online Field Experiment in Japan
thanks: |
  This study is conducted as a part of the Project "Implementation of EBPM in Japan"
  undertaken at the Research Institute of Economy, Trade and Industry (RIETI).
  In completing this paper,
  we thank participants of the EBPM Study Group and
  the Discussion Paper Study Group of RIETI for their insightful comments.
  This research is financially supported by
  the Japan Society for the Promotion of Science
  [JSPS Grant Number: 20H05632 (F., Ohtake)]
  and the Ministry of Health, Labor, and Welfare.
  Prior to conducting a randomized controlled trial on an online survey,
  this study was approved by the Institutional Review Board
  of the Graduate School of Economics, Osaka University (R020114).
abstract: |
  This study conducted a randomized controlled trial (RCT) in a nationwide online survey
  to examine which text-based nudges best promote rubella antibody testing and vaccination.
  The main results are as follows.
  First, the altruistic message,
  which emphasizes that the fetus's health could be impaired by
  infecting women in the early stages of pregnancy with rubella,
  has a positive effect on the intention and behavior relating to the antibody test among men,
  who had automatically received a free coupon from the local government in 2019.
  Second, most people who test negative for antibodies (do not have antibodies),
  regardless of the type of nudge messages or whether or not they have received the coupon,
  have since been vaccinated.
  This result suggests that policies to increase antibody testing of pre-test individuals
  should be prioritized over those to increase vaccination of post-test negatives.
  Third, text-based messages have no statistically significant effect
  among men who had to apply for coupons themselves in 2019.
keyword:
  words: Rubella, Vaccination, Antibody Test, Text-Based Nudges
  JEL: D90, I12, I18
author: 
  - name: Hiroki Kato
    inst: Graduate School of Economics, Osaka University
    email: h-kato\@econ.osaka-u.ac.jp
  - name: Shusaku Sasaki
    inst: Center for Infectious Disease Education and Research, Osaka University
  - name: Fumio Ohtake
    inst: |
      Graduate School of Economics, Osaka University.
      Center for Infectious Disease Education and Research, Osaka University
date: "`r format(Sys.time(), '%Y/%m/%d')`"
csl: template/csl/elsevier-harvard.csl
bibliography: MHLW Rubella Nudge.bib
documentclass: article
papersize: a4
fontsize: 11pt
geometry: "left=3cm,right=3cm,top=3cm,bottom=3cm"
graphics: yes
indent: yes
linespace: 1.5
output:
  bookdown::pdf_document2:
    latex_engine: xelatex
    number_sections: yes
    keep_tex: yes
    fig_caption: yes
    toc: false
    dev: cairo_pdf
    extra_dependencies: ["float"]
    template: "template/tex/plain.tex"
  # bookdown::word_document2:
  #   dev: png
params:
  preview: false
  appendix: false
---

```{r render, eval = FALSE, include = FALSE, echo = FALSE}
library(here)
rmarkdown::render(
  input = here("0-root.rmd"),
  output_format = "all",
  output_file = "body",
  output_dir = "publish"
)

# direct complie via tinytex
# tinytex::xelatex("publish/RIETI/webRCT/webRCT.tex")
```

```{r include = FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  echo = FALSE,
  cache = FALSE,
  include = TRUE,
  fig.pos = "t",
  fig.width = 10,
  fig.height = 6
)

format <- knitr::opts_knit$get("rmarkdown.pandoc.to")
out <- switch(format,
  "latex" = "kableExtra",
  "docx" = "flextable"
)

library(systemfonts)
data.frame(unique(system_fonts()[, "family"]))
grDevices::windowsFonts(YuGothic = grDevices::windowsFont("Yu Gothic"))

library(RCTtoolbox)
options(
  knitr.kable.NA = " ",
  knitr.table.format = "latex",
  modelsummary_stars_note = FALSE,
  modelsummary_format_numeric_latex = "plain",
  RCTtoolbox.table_output = out,
  RCTtoolbox.table_fontsize = 9,
  RCTtoolbox.plot_family = "Yu Gothic"
)
```

# はじめに {#intro}

```{r child = "1-introduction.rmd", eval = FALSE}

```

# 日本における風しんワクチンの背景 {#background}

```{r child = "2-background.rmd", eval = FALSE}

```

# オンライン調査の概要 {#experiment}

```{r child = "3-experiment.rmd", eval = FALSE}

```


# Results {#result}

## Effect of Text-Based Nudges on Intentions

```{r}
library(here)
knitr::spin_child(here("code", "4-selection1-intention.r"))
```

```{r child = "4-result-coupon1.rmd", eval = FALSE}

```

```{r child = "5-result-money.rmd", eval = FALSE}

```

```{r child = "6-result-coupon0.rmd", eval = FALSE}

```

# 議論と結論 {#conclusion}

```{r child = "7-conclusion.rmd", eval = FALSE}

```

\newpage

# 参考文献 {-}
