---
title: Result(1)
subtitle: Preview
author: Hiroki Kato
bibliography: MHLW Rubella Nudge.bib
output:
  bookdown::html_document2:
    toc: true
    toc_float: true
    number_sections: false
params:
  preview: true
  appendix: true
---

```{r eval = FALSE, include = FALSE, echo = FALSE}
library(here)
rmarkdown::render(
  input = here("4-result-coupon1.rmd"),
  output_format = "all",
  output_dir = "report/view"
)
```

```{r include = FALSE, eval = params$preview}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  echo = FALSE,
  cache = FALSE,
  include = TRUE,
  fig.width = 10
)

out <- "kableExtra"
options(
  knitr.kable.NA = " ",
  knitr.table.format = "html",
  modelsummary_stars_note = FALSE
)

library(systemfonts)
data.frame(unique(system_fonts()[, "family"]))
grDevices::windowsFonts(YuGothic = grDevices::windowsFont("Yu Gothic"))
```

```{r include = FALSE}
knitr::spin_child(here("code/3-selection1-coupon1.r"))
```

```{asis, echo = params$preview|!params$appendix}
## サンプルセレクションの定義 {#selection}

我々の関心はナッジ・メッセージが抗体検査やワクチン接種を受けていない男性の行動を促進できるかどうかである。
そのために、第1回調査時点で抗体検査とワクチン接種を受けていない男性にサンプルを限定して、
ナッジ・メッセージの効果を推定する。
分析に用いるサンプルの基準は2つある。
第一の基準は第1回調査で過去に抗体検査を受検したもしくは過去にワクチン接種をしていないと回答したかどうかである。
抗体検査の受検やワクチン接種の意向に対する効果を推定するとき、
この基準を満たした男性にサンプルを限定する（以降、Wave 1セレクションデータと呼ぶ）。
第二の基準は第2回調査で第1回調査以前に抗体検査を受検したもしくはワクチンを接種したと回答したかどうかである[^reason]。
第1回調査以降の抗体検査の受検やワクチン接種に対する効果を推定するとき、
第一の基準と第二の基準を満たした男性にサンプルを限定する（以降、Wave 2セレクションデータと呼ぶ）。

[^reason]: 第1回調査以降に自身の接種歴を調べ直すなどによって、第1回調査と第2回調査の回答に違いが生じる可能性がある。
そのため、どちらかの調査で第1回調査以前に抗体検査を受検したもしくはワクチンを接種したと回答した人を除いた。

我々は上記の基準で構築したサブサンプルを2019年度にクーポン券の送付対象年齢か否かで分割して、
各グループにおけるナッジ・メッセージの効果を推定する。
2019年度にクーポン券の送付対象年齢か否かは2019年4月時点の年齢で識別した。
各市区町村は2019年度に40歳以上46歳以下の男性のクーポン券を送付し、
2020年度以降に47歳以上56歳以下の男性のクーポン券を送付する。
ただし、市区町村の判断や本人の希望に応じて、47歳以上56歳以下の男性もクーポン券を受け取ることはできる。

## 2019年度クーポン券配布対象者に限定したナッジ・メッセージの効果 {#coupon1}
```

```{r show-int-coupon1-balance, ref.label="int-coupon1-balance", eval = params$preview|params$appendix}

```

```{r show-act-coupon1-balance, ref.label="act-coupon1-balance", eval = params$preview|params$appendix}

```

```{r show-coupon1-power, ref.label="coupon1-power", results = "asis", eval = params$preview|!params$appendix}

```

```{r show-int-coupon1-ttest, ref.label = "int-coupon1-ttest", fig.cap = "2019年度クーポン券配布対象者に限定した意向に対するナッジ・メッセージの効果。データソース：Wave 1セレクションデータ。注）図中の数値は各群の比率を示す。星印は厚労省メッセージ群との平均値の差のt検定の結果であり、次の規則に従う：* p < 0.1、** p < 0.05、*** p < 0.01。", out.extra="", eval = params$preview|!params$appendix}

```

```{asis, echo = params$preview|!params$appendix}
図\@ref(fig:show-int-coupon1-ttest)のパネルAは
各介入群の抗体検査受検の意向を示している。
結果として、
利他強調メッセージは厚労省メッセージよりも抗体検査受検の意向を高めている。
厚労省メッセージを読んだ人の約20.8%が抗体検査を受けたいと回答している一方で、
利他強調メッセージを読んだ人の約35.1%が抗体検査を受けたいと回答している。
したがって、
利他強調メッセージはコントロールよりも
約14.3%ポイント抗体検査の受検意向を引き上げており、
これはt検定より統計的に1%水準で有意である。
その他のナッジ・メッセージについては、
抗体検査を受けたいと答えた人の割合は30%を下回っていて、
その比率が厚労省メッセージと等しいという帰無仮説を棄却できない。

図\@ref(fig:show-int-coupon1-ttest)のパネルBは
各介入群のワクチン接種の意向を示している。
その結果、すべてのナッジ・メッセージ群における比率は40%から45%の範囲にあり、
それが厚労省メッセージの比率と統計的に有意な差とならなかった。
考えられる可能性の一つはワクチン接種の意向の質問文による刺激である。
我々は抗体を持っていないという条件のもとで接種したいかどうかを質問しているので、
質問文がワクチン接種の必要性を強く刺激した可能性がある。
```

```{r show-act-coupon1-ttest, ref.label = "act-coupon1-ttest", fig.cap = "2019年度クーポン券配布対象者に限定した行動に対するナッジ・メッセージの効果。データソース：Wave 2セレクションデータ。注）図中の数値は各群の比率を示す。星印は厚労省メッセージ群との平均値の差のt検定の結果であり、次の規則に従う：* p < 0.1、** p < 0.05、*** p < 0.01。", out.extra="", eval = params$preview|!params$appendix}

```

```{asis, echo = params$preview|!params$appendix}
図\@ref(fig:show-act-coupon1-ttest)のパネルAは各介入群の第1回調査以降の抗体検査受検比率を示している。
結果として、利他強調メッセージと利己強調メッセージでは、厚労省メッセージよりも
第1回調査以降の抗体検査の受検比率が高い。
厚労省メッセージを読んだ人の約3.5%は第1回調査以降に抗体検査を受検している。
その一方で、利他強調メッセージを読んだ人の約10.9%と
利己強調メッセージを読んだ人の約9%は第1回調査以降に抗体検査を受検している。
したがって、利他強調メッセージはコントロールに比べて7.4%ポイント抗体検査の受検率を引き上げており、
これはt検定より統計的に5%水準で有意である。
また、利己強調メッセージはコントロールよりも約5.5%ポイント高く、これはt検定より統計的に10%水準で有意である。

図\@ref(fig:show-act-coupon1-ttest)のパネルBは
各介入群の第1回調査以降の抗体検査とワクチン接種を両方受けた人の比率（以降、ワクチン接種率と呼ぶ）を示している。
この比率は今回の厚生労働省の政策によって新たに抗体を獲得した人の比率を示すので、
政策効果のアウトカム指標となる。
その結果、利他強調メッセージと社会比較メッセージがワクチン接種を促進していることがわかる。
厚労省メッセージを読んだ人の約0.9%が抗体検査を受検し、ワクチンを接種している。
その一方で、利他強調メッセージを読んだ人の約4.7%と
社会比較メッセージを読んだ人の約4.9%が第1回調査以降に抗体検査を受検し、ワクチンを接種している。
よって、利他強調メッセージは3.8%ポイントコントロールよりも高く、これはt検定より統計的に10%水準で有意である。
社会比較メッセージは4%ポイントコントロールよりも高く、これはt検定より統計的に10%水準で有意である。

<!--
[^policy]: この効果は今回の厚生労働省の政策によって新たに抗体を獲得した人の比率を示すので、政策効果である。
利他強調メッセージと社会比較メッセージは厚生労働省の追加政策の対象男性の抗体保有率を約4%ポイント高めていて、
これは厚生労働省の目標である10%ポイント増加の約40%に相当する。
-->
```

```{r show-int-coupon1-reg, ref.label = "int-coupon1-reg", eval = params$preview|params$appendix}

```

```{r show-act-coupon1-reg, ref.label="act-coupon1-reg", eval = params$preview|params$appendix}

```

```{asis, echo = params$preview|!params$appendix}
補論\@ref(addtab)の表\@ref(tab:show-int-coupon1-reg)
と表\@ref(tab:show-act-coupon1-reg)に厚労省メッセージ群を比較対象とした
ナッジ・メッセージの線形確率モデルの推定結果を示した。
ここまでの結果は個人の観察可能な特徴をコントロールしても変化しない。
それに加えて、共変量を制御したモデルを推定すると、
利己強調メッセージは厚労省メッセージよりも抗体検査受検の意向を約9%ポイント強めていて、
これは統計的に10%水準で有意である。
さらに、利己強調メッセージと社会比較メッセージは厚労省メッセージと比較して抗体検査の受検行動に
統計的に5%水準で正の影響を与えている。
効果の規模はそれぞれ6.7%ポイントと6.5%ポイントである。
```

```{r show-int-coupon1-altreg, ref.label="int-coupon1-altreg", eval = params$preview|params$appendix}

```

```{r show-act-coupon1-altreg, ref.label = "act-coupon1-altreg", eval = params$preview|params$appendix}

```

```{asis, echo = params$preview|!params$appendix}
また、効果の規模が最も大きい利他強調メッセージ群を比較対象とした
線形確率モデルの推定結果を補論\@ref(addtab)の
表\@ref(tab:show-int-coupon1-altreg)と
表\@ref(tab:show-act-coupon1-altreg)に示した。
その結果、
利己強調メッセージ群の抗体検査受検の意向は利他強調メッセージのそれと統計的に有意な差とならなかった。
さらに、利己強調メッセージと社会比較メッセージの抗体検査の受検比率は
利他強調メッセージのそれと統計的に有意に異ならならなかった。
したがって、効果があった利他強調メッセージとの有意差がないという意味で、
利己強調メッセージは抗体検査受検の意向と行動を促進した可能性があり、
社会比較メッセージは抗体検査の受検を促進した可能性がある。
しかしながら、抗体検査の受検比率の差は検出力を十分に保つほどの大きさではないので、
サンプルサイズを十分に大きくして検証する必要がある。
```

```{r show-tester-coupon1, ref.label = "tester-coupon1", eval = params$preview|!params$appendix}

```

```{asis, echo = params$preview|!params$appendix}
我々のサーベイには抗体検査の結果の情報があるので、
その変数を用いて先の結果に関するメカニズムを議論しよう。
そのために、我々は抗体検査を受検した人に限定して、
抗体検査の結果とトリートメント群のクロス集計と、
ワクチン接種とトリートメント群のクロス集計を作成し、
それを表\@ref(tab:show-tester-coupon1)に示した。

この表から二つの発見がある。
第一に、各群の陰性者のワクチン接種率は60%から100%の範囲にある。
たとえば、利他強調メッセージを割り当てられた抗体検査受検者は14人いるが、
そのうち7人が抗体を保有していなかった。
さらに、制度上、陰性者のみがワクチンを接種するので、
抗体を保有していない7人のうち6人がワクチンを接種している。
よって、陰性者のワクチン接種率は85.7%（$=6/7$）である。
また、サンプルをトリートメント群で分割しない場合、陰性者のワクチン接種率は87.5%であり、
その95%信頼区間は100%を含んでいる[^bootstrap]。
したがって、介入に関わらず抗体検査の結果が陰性である人のほとんどがワクチンを接種している。
```

```{r show-negative-vaccine-coupon1, ref.label="negative-vaccine-coupon1", results = "asis", eval = params$preview|!params$appendix}
```

```{asis, echo = params$preview|!params$appendix}
第二に、各群の抗体検査の陰性比率は20%から62.5%の範囲にある。
たとえば、利他強調メッセージを割り当てられた抗体検査受検者14人のうち、
7人が抗体を保有していなかったので、陰性比率は50%である。
また、厚労省メッセージ群と社会比較メッセージ群における陰性比率はそれぞれ
25%（$=1/4$）と55%（$=5/9$）である。
したがって、利他強調メッセージと社会比較メッセージは
厚労省メッセージよりも抗体検査の受検を促進しただけでなく、
ワクチンを接種する必要のある受検者が多くいたので、ワクチン接種に対して正の効果があった。
逆に、利己強調メッセージの陰性比率は30%（$=3/10$）であり、
厚労省メッセージ群のそれと近い値になったので、
抗体検査の受検に対して正の効果があるにも関わらず、
ワクチン接種に対して統計的に有意でなかった。
ただし、群間で陰性比率が大きく異なるという結果は母集団では当てはまらない可能性が高い[^Bayesian]。
ナッジ・メッセージの割り当てと陰性という事象が独立であるという帰無仮説を
フィッシャーの正確検定で検証したところ、
我々はその帰無仮説を棄却できなかった（p値=0.543）。
```

```{r show-bayesian-coupon1, ref.label="bayesian-coupon1", results = "asis", eval = params$preview|!params$appendix}
```