---
title: Result(2)
subtitle: Preview
author: Hiroki Kato
bibliography: MHLW Rubella Nudge.bib
output:
  bookdown::html_document2:
    toc: true
    toc_float: true
    number_sections: false
params:
  preview: true
  appendix: true
---

```{r eval = FALSE, include = FALSE, echo = FALSE}
library(here)
rmarkdown::render(
  input = here("5-result-money.rmd"),
  output_format = "all",
  output_dir = "report/view"
)
```

```{r include = FALSE, eval = params$preview}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  echo = FALSE,
  cache = FALSE,
  include = TRUE,
  fig.width = 10
)

out <- "kableExtra"
options(
  knitr.kable.NA = " ",
  knitr.table.format = "html",
  modelsummary_stars_note = FALSE
)

library(systemfonts)
data.frame(unique(system_fonts()[, "family"]))
grDevices::windowsFonts(YuGothic = grDevices::windowsFont("Yu Gothic"))
```

```{r include = FALSE}
knitr::spin_child(here("code/4-selection1-money.r"))
```

```{r show-demand-vaccine, ref.label="demand-vaccine", fig.cap = "2019年度クーポン券配布対象者の風しんワクチンの需要曲線。データソース：Wave 1セレクションデータ。注）黒の三角はワクチン接種費用が無料であるときの接種割合と厚労省メッセージの抗体検査受検率を合計した割合と、それに対応するWTPを示している。", out.extra="", eval = params$preview|!params$appendix}

```

```{asis, echo = params$preview|!params$appendix}

## ナッジ・メッセージの金銭的価値 {#econvalue}

2019年度のクーポン券送付者におけるナッジ・メッセージの効果を金銭的な価値で評価することを試みる。
そのために、第1回調査のナッジ・メッセージを示す前の質問票Aで調査したワクチン接種の支払意思額を用いる。
ワクチンの価格は5000円と仮定して、我々は、自治体の補助金額が$s_j$のとき、ワクチン接種をするかどうかを調査した。
補助金額は$s_j \in \{0, 1000, 2000, \ldots, 10000\}$とした。
回答者$i$が接種すると回答した最低の補助金額を$s_i^{\text{min}}$とする。
回答者$i$が接種しないと回答した最高の補助金額を$s_i^{\text{max}}$とする。
このとき、回答者$i$の支払意思額は
$[5000 - s_i^{\text{min}}, 5000 - s_i^{\text{max}})$の範囲内で識別される[^extreme]。
したがって、追加の仮定を置かない限り、ワクチン接種の需要曲線はステップワイズな曲線となり、
メッセージの金銭的価値は範囲で得られる。

メッセージの金銭的価値を点推定するために、
我々は支払意思額が$[5000 - s_i^{\text{min}}, 5000 - s_i^{\text{max}})$の範囲で識別されるとき、
真の支払意思額はその範囲内で一様に分布することを仮定する。
このとき、ステップワイズなワクチン接種の需要曲線は線型補間で表される。
図\@ref(fig:show-demand-vaccine)はこの仮定のもとで、2019年度に自動的にクーポン券を受け取る人に限定した
風しんワクチン接種の需要曲線である。
我々はこの需要曲線を用いて、メッセージの金銭的価値を算出する。

[^extreme]: 回答者がすべての補助金額$s_j$のときの接種しないと回答したならば、$s_i^{\text{max}} = 10000$である。しかしながら、$s_i^{\text{min}}$はデータで定義できない。そこで、$s_i^{\text{min}} = 11000$と仮定した。ただし、後に示すが、この仮定はナッジ・メッセージの金銭的価値に影響を与えない。
```

```{r show-economic-value, ref.label="economic-value", eval = params$preview|!params$appendix}

```

```{asis, echo = params$preview|!params$appendix}
ナッジ・メッセージの金銭的な価値を次のように計算する。
はじめに、ベースラインの接種割合を決める。
図\@ref(fig:show-demand-vaccine)の需要曲線は無料クーポンが発行される人に限定しているので、
ワクチンの供給曲線はゼロで水平である。
このときの接種割合は約66.5%である。
ベースラインの接種割合はこの割合に厚労省メッセージの抗体検査受検率を足したものとする[^assumption]。
ベースラインの接種割合は約70%であり、対応する支払意思額は約-394円である。

次に、接種割合をベースラインの均衡点からナッジ・メッセージの効果分だけ増やすとき、
需要曲線上で対応する支払意思額を見つける。
その支払意思額はナッジ・メッセージの効果量だけ増やすのに必要な自治体の追加的な補助金額であり、
それがナッジ・メッセージの一人当たりの金銭的価値である。
たとえば、ベースラインの均衡点の接種割合とナッジ・メッセージの効果の和が0.8であるとき、
需要曲線上で対応する支払意思額は約-4280円である。
すなわち、ナッジ・メッセージの効果量分だけ接種割合を増やすために、
自治体は一人当たり約3886（$=4280-394$）円の追加的な補助金を支払う必要がある。

[^assumption]: 抗体検査の結果が陰性である人のほとんどはワクチンを接種しているので、
抗体検査の受検率をワクチン接種率として用いる。

我々は抗体検査受検に対するナッジ・メッセージの効果を用いる。
表\@ref(tab:show-tester-coupon1)で示したように、
抗体検査の結果が陰性である人のほとんどはワクチンを接種している。
したがって、抗体検査受検に対するナッジ・メッセージの効果をワクチン接種に対する効果とみなせる。

表\@ref(tab:show-economic-value)はメッセージの金銭的価値の試算結果である。
第2列は図\@ref(fig:show-act-coupon1-ttest)のパネルAで示したメッセージの効果を示している。
第3列はベースラインの均衡点の接種割合からメッセージの効果量分だけ増やしたときの接種割合を示している。
第4列はメッセージの一人当たりの金銭的価値である。
この金銭的価値をアメリカドルに換算した結果を第6列に示している。
抗体検査の受検を促進した利他強調メッセージの一人当たりの金銭的価値は約2000円（約18ドル）である。

<!-- 参考：https://www.mhlw.go.jp/content/10906000/000645181.pdf -->
また、メッセージ自体の金銭的価値の総額は一人当たりの金銭的価値と
2019年度に発行されたクーポン券をまだ利用していない人数の積で得られる。
厚生労働省より、2019年度にクーポン券が発行されたにもかかわらず、
1月時点で抗体検査のクーポン券を利用していない人は約529万人である。
表\@ref(tab:show-economic-value)の第5列はメッセージの金銭的価値の総額を示している。
第7列はそれをアメリカドルに換算した結果を示している。
利他強調メッセージの金銭的価値の総額は約100億円である。
```