---
title: |
  Supplementary Material (Not for Publication):
  "Adding Nudge-based Reminders to Financial Incentives for Promoting Antibody Testing and Vaccination to Prevent the Spread of Rubella"
author:
  - name: Hiroki Kato
    inst-id: a
  - name: Shusaku Sasaki
    inst-id: b
  - name: Fumio Ohtake
    inst-id: b
inst:
  - id: a
    name: Graduate School of Economics, Osaka University
  - id: b
    name: Center for Infectious Disease Education and Research (CiDER), Osaka University
biblio-style: agsm
bibliography: text-message-2020RCT.bib
output:
  bookdown::pdf_document2:
    latex_engine: pdflatex
    template: template/my-template.tex
    keep_tex: true
    citation_package: natbib
    toc: true
base-strech: 1.5
---

```{r chunk-option, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  error = FALSE,
  message = FALSE,
  dev = "pdf",
  fig.width = 15,
  fig.height = 8,
  fig.pos = "t",
  out.extra = ""
)
```

```{r source-file}
library(here)
source(here("R/R6_StartAnalysis.r"))

options(
  knitr.table.format = "latex",
  knitr.kable.NA = "",
  modelsummary_stars_note = FALSE,
  modelsummary_factory_default = "latex"
)
```

```{r def-class}
ctrl <- c(
  "age", "married", "education",
  "income", "noinfo_income",
  "exercise_w1", "health_check", "flushot", "norm_waiting_line", "selfish_anonymous",
  "handwash", "temp_check", "avoid_out", "avoid_crowd", "wear_mask"
)

setup <- StartAnalysis$new(here("data/online_survey.csv"))
setup$add_control(ctrl)
main <- setup$main()
```

```{r nudge-label}
nudge_labels <- c(
  "MHLW (Control)",
  "MHLW (Age)",
  "Altruistic",
  "Selfish",
  "Social Comparison",
  "Deadline",
  "Convenient"
)
```

# RDD

```{r rdd-int}
est <- main$wave1 %>%
  dplyr::filter(age %in% 46:47) %>%
  group_by(nudge) %>%
  nest() %>%
  ungroup() %>%
  mutate(
    test = map(
      data,
      ~ lm_robust(outcome_test ~ coupon2019, data = ., se_type = "stata")
    ),
    vacc = map(
      data,
      ~ lm_robust(outcome_vacc ~ coupon2019, data = ., se_type = "stata")
    )
  ) %>%
  mutate(
    test_tidy = map(test, broom::tidy),
    test_glan = map(test, broom::glance),
    test_coef = map_dbl(test_tidy, ~ .[2, "estimate"]),
    test_se = map_dbl(test_tidy, ~ .[2, "std.error"]),
    test_p = map_dbl(test_tidy, ~ .[2, "p.value"]),
    test_n = map_int(test_glan, ~ .[1, "nobs"]),
    vacc_tidy = map(vacc, broom::tidy),
    vacc_glan = map(vacc, broom::glance),
    vacc_coef = map_dbl(vacc_tidy, ~ .[2, "estimate"]),
    vacc_se = map_dbl(vacc_tidy, ~ .[2, "std.error"]),
    vacc_p = map_dbl(vacc_tidy, ~ .[2, "p.value"]),
    vacc_n = map_int(vacc_glan, ~ .[1, "nobs"])
  ) %>%
  select(nudge, test_coef:test_n, vacc_coef:vacc_n)

est %>%
  arrange(nudge) %>%
  mutate(nudge = factor(nudge, levels = LETTERS[1:7], labels = nudge_labels)) %>%
  knitr::kable(
    caption = "Effect of Default Incentive on Intentions near Threshold",
    col.names = c("Group", rep(c("Est", "SE", "P", "N"), 2)),
    digits = 3,
    align = "lcccccccc",
    booktabs = TRUE,
    linesep = ""
  ) %>%
  kableExtra::kable_styling(font_size = 10, latex_options = "HOLD_position") %>%
  kableExtra::add_header_above(c(" " = 1, "Testing" = 4, "Vaccination" = 4)) %>%
  kableExtra::footnote(
    general_title = "",
    general = "Notes: We used respondents aged 46 or 47 years old.",
    threeparttable = TRUE,
    escape = FALSE
  )
```

```{r rdd-act}
est <- main$wave2 %>%
  dplyr::filter(age %in% 45:48) %>%
  group_by(nudge) %>%
  nest() %>%
  ungroup() %>%
  mutate(
    test = map(
      data,
      ~ lm_robust(outcome_test ~ coupon2019, data = ., se_type = "stata")
    ),
    vacc = map(
      data,
      ~ lm_robust(outcome_vacc ~ coupon2019, data = ., se_type = "stata")
    )
  ) %>%
  mutate(
    test_tidy = map(test, broom::tidy),
    test_glan = map(test, broom::glance),
    test_coef = map_dbl(test_tidy, ~ .[2, "estimate"]),
    test_se = map_dbl(test_tidy, ~ .[2, "std.error"]),
    test_p = map_dbl(test_tidy, ~ .[2, "p.value"]),
    test_n = map_int(test_glan, ~ .[1, "nobs"]),
    vacc_tidy = map(vacc, broom::tidy),
    vacc_glan = map(vacc, broom::glance),
    vacc_coef = map_dbl(vacc_tidy, ~ .[2, "estimate"]),
    vacc_se = map_dbl(vacc_tidy, ~ .[2, "std.error"]),
    vacc_p = map_dbl(vacc_tidy, ~ .[2, "p.value"]),
    vacc_n = map_int(vacc_glan, ~ .[1, "nobs"])
  ) %>%
  select(nudge, test_coef:test_n, vacc_coef:vacc_n)

est %>%
  arrange(nudge) %>%
  mutate(nudge = factor(nudge, levels = LETTERS[1:7], labels = nudge_labels)) %>%
  knitr::kable(
    caption = "Effect of Default Incentive on Behavior near Threshold",
    col.names = c("Group", rep(c("Est", "SE", "P", "N"), 2)),
    digits = 3,
    align = "lcccccccc",
    booktabs = TRUE,
    linesep = ""
  ) %>%
  kableExtra::kable_styling(font_size = 10, latex_options = "HOLD_position") %>%
  kableExtra::add_header_above(c(" " = 1, "Testing" = 4, "Vaccination" = 4)) %>%
  kableExtra::footnote(
    general_title = "",
    general = "Notes: We used respondents aged 45--48 years old.",
    threeparttable = TRUE,
    escape = FALSE
  )
```

# Using Wave 2 to Examine Effect on Intentions

```{r wave2-test-int, fig.pos = 'H', fig.cap = 'Effect on Intention of Testing Using Wave 2 Data'}
stats <- main$wave2 %>%
  mutate(test_int = test_int * 100) %>%
  select(test_int, nudge, coupon2019) %>%
  group_by(coupon2019, nudge) %>%
  summarize(
    mu = mean(test_int),
    se = se(test_int)
  )

x <- main$wave2$nudge
y <- main$wave2$test_int
default <- main$wave2$coupon2019

t_optin <- LETTERS[1:7] %>%
  sapply(function(i) t.test(y[x == "A" & default == 0], y[x == i & default == 0])$p.value)

t_default <- LETTERS[1:7] %>%
  sapply(function(i) t.test(y[x == "A" & default == 1], y[x == i & default == 1])$p.value)

t_res <- tibble(
  nudge = c(names(t_optin), names(t_default)),
  coupon2019 = c(rep(0, length(t_optin)), rep(1, length(t_default))),
  p = c(t_optin, t_default)
)

coupon2019_labels <- c(
  sprintf("A. Default incentive group (N = %1d)", sum(default == 1)),
  sprintf("B. Opt-in incentive group (N = %1d)", sum(default == 0))
)

plot_data <- stats %>%
  left_join(t_res, by = c("nudge", "coupon2019")) %>%
  mutate(
    nudge = factor(nudge, labels = nudge_labels),
    coupon2019 = factor(coupon2019, levels = c(1, 0), labels = coupon2019_labels),
    mu_label = sprintf("%1.1f%%", mu),
    p_label = sprintf("[p=%1.3f]", p),
    p_label = if_else(p_label == "[p=0.000]", "[p<0.001]", p_label),
    label = paste(mu_label, p_label)
  )

plot_data %>%
  ggplot(aes(x = fct_rev(nudge), y = mu, ymin = mu - se, ymax = mu + se)) +
  geom_hline(aes(yintercept = 0)) +
  geom_bar(stat = "identity", fill = "grey80", color = "black") +
  geom_errorbar(width = 0.5) +
  geom_text(aes(y = 50, label = label), size = 5) +
  labs(x = "Treatments", y = "Proportion (%)") +
  facet_wrap(~coupon2019, ncol = 1, scales = "free") +
  scale_y_continuous(limits = c(0, 60), breaks = seq(0, 60, by = 10)) +
  coord_flip() +
  theme_classic(base_size = 15) +
  theme(
    strip.background = element_blank(),
    strip.text = element_text(size = 16, hjust = 0)
  )
```

```{r wave2-vacc-int, fig.pos = 'H', fig.cap = 'Effect on Intention of Vaccination Using Wave 2 Data'}
stats <- main$wave2 %>%
  mutate(outcome = vaccine_int * 100) %>%
  select(outcome, nudge, coupon2019) %>%
  group_by(coupon2019, nudge) %>%
  summarize(
    mu = mean(outcome),
    se = se(outcome)
  )

x <- main$wave2$nudge
y <- main$wave2$vaccine_int
default <- main$wave2$coupon2019

t_optin <- LETTERS[1:7] %>%
  sapply(function(i) t.test(y[x == "A" & default == 0], y[x == i & default == 0])$p.value)

t_default <- LETTERS[1:7] %>%
  sapply(function(i) t.test(y[x == "A" & default == 1], y[x == i & default == 1])$p.value)

t_res <- tibble(
  nudge = c(names(t_optin), names(t_default)),
  coupon2019 = c(rep(0, length(t_optin)), rep(1, length(t_default))),
  p = c(t_optin, t_default)
)

coupon2019_labels <- c(
  sprintf("A. Default incentive group (N = %1d)", sum(default == 1)),
  sprintf("B. Opt-in incentive group (N = %1d)", sum(default == 0))
)

plot_data <- stats %>%
  left_join(t_res, by = c("nudge", "coupon2019")) %>%
  mutate(
    nudge = factor(nudge, labels = nudge_labels),
    coupon2019 = factor(coupon2019, levels = c(1, 0), labels = coupon2019_labels),
    mu_label = sprintf("%1.1f%%", mu),
    p_label = sprintf("[p=%1.3f]", p),
    p_label = if_else(p_label == "[p=0.000]", "[p<0.001]", p_label),
    label = paste(mu_label, p_label)
  )

plot_data %>%
  ggplot(aes(x = fct_rev(nudge), y = mu, ymin = mu - se, ymax = mu + se)) +
  geom_hline(aes(yintercept = 0)) +
  geom_bar(stat = "identity", fill = "grey80", color = "black") +
  geom_errorbar(width = 0.5) +
  geom_text(aes(y = 65, label = label), size = 5) +
  labs(x = "Treatments", y = "Proportion (%)") +
  facet_wrap(~coupon2019, ncol = 1, scales = "free") +
  scale_y_continuous(limits = c(0, 80), breaks = seq(0, 80, by = 10)) +
  coord_flip() +
  theme_classic(base_size = 15) +
  theme(
    strip.background = element_blank(),
    strip.text = element_text(size = 16, hjust = 0)
  )
```

# Investigate Consistent Response

```{r attrition-follow}
dt <- setup$data %>%
  dplyr::filter(40 <= age & age <= 56) %>%
  mutate(
    wave1 = if_else(exp_antibody != 1 & exp_vaccine != 1, "Yes", "No"),
    wave2 = if_else(act_test != 2 & act_vaccine != 2, "Yes", "No")
  )

subset(dt, follow == 1) %>%
  datasummary_crosstab(
    wave1 ~ wave2,
    title = "Have you not been both tested for antibodies and vaccinated before Wave 1?",
    data = .
  ) %>%
  kableExtra::kable_styling(latex_options = "HOLD_position") %>%
  kableExtra::add_header_above(c(" " = 2, "wave 2" = 2, " " = 1)) %>%
  kableExtra::footnote(
    general_title = "",
    general = "Notes: We used respondents who participated in Wave 2.",
    threeparttable = TRUE,
    escape = FALSE
  )
```

```{r attrition-not-follow}
subset(dt, follow == 0) %>%
  datasummary(
    wave1 ~ N + Percent("col"),
    title = "Have you not been both tested for antibodies and vaccinated before Wave 1?",
    data = .
  ) %>%
  kableExtra::kable_styling(latex_options = "HOLD_position") %>%
  kableExtra::footnote(
    general_title = "",
    general = "Notes: We used respondents who did not participated in Wave 2.",
    threeparttable = TRUE,
    escape = FALSE
  )
```

# Effect on Looking over Program

```{r effect-program, fig.pos = "H", fig.cap = "Effect on Looking over Vaccination Program"}
stats <- main$wave2 %>%
  mutate(outcome = check_program * 100) %>%
  select(outcome, nudge, coupon2019) %>%
  group_by(coupon2019, nudge) %>%
  summarize(
    mu = mean(outcome),
    se = se(outcome)
  )

x <- main$wave2$nudge
y <- main$wave2$check_program
default <- main$wave2$coupon2019

t_optin <- LETTERS[1:7] %>%
  sapply(function(i) t.test(y[x == "A" & default == 0], y[x == i & default == 0])$p.value)

t_default <- LETTERS[1:7] %>%
  sapply(function(i) t.test(y[x == "A" & default == 1], y[x == i & default == 1])$p.value)

t_res <- tibble(
  nudge = c(names(t_optin), names(t_default)),
  coupon2019 = c(rep(0, length(t_optin)), rep(1, length(t_default))),
  p = c(t_optin, t_default)
)

coupon2019_labels <- c(
  sprintf("A. Default incentive group (N = %1d)", sum(default == 1)),
  sprintf("B. Opt-in incentive group (N = %1d)", sum(default == 0))
)

plot_data <- stats %>%
  left_join(t_res, by = c("nudge", "coupon2019")) %>%
  mutate(
    nudge = factor(nudge, labels = nudge_labels),
    coupon2019 = factor(coupon2019, levels = c(1, 0), labels = coupon2019_labels),
    mu_label = sprintf("%1.1f%%", mu),
    p_label = sprintf("[p=%1.3f]", p),
    p_label = if_else(p_label == "[p=0.000]", "[p<0.001]", p_label),
    label = paste(mu_label, p_label)
  )

plot_data %>%
  ggplot(aes(x = fct_rev(nudge), y = mu, ymin = mu - se, ymax = mu + se)) +
  geom_hline(aes(yintercept = 0)) +
  geom_bar(stat = "identity", fill = "grey80", color = "black") +
  geom_errorbar(width = 0.5) +
  geom_text(aes(y = 45, label = label), size = 5) +
  labs(x = "Treatments", y = "Proportion (%)") +
  facet_wrap(~coupon2019, ncol = 1, scales = "free") +
  scale_y_continuous(limits = c(0, 70), breaks = seq(0, 70, by = 10)) +
  coord_flip() +
  theme_classic(base_size = 15) +
  theme(
    strip.background = element_blank(),
    strip.text = element_text(size = 16, hjust = 0)
  )
```