---
title: |
  Appendix
  "Text-Based Nudges Promoting Rubella Antibody Testing and Vaccination:
  Evidence from Nationwide Online Field Experiment in Japan"
date: "`r format(Sys.time(), '%Y/%m/%d')`"
csl: template/csl/elsevier-harvard.csl
bibliography: MHLW Rubella Nudge.bib
documentclass: article
papersize: a4
fontsize: 11pt
geometry: "left=3cm,right=3cm,top=3cm,bottom=3cm"
graphics: yes
indent: yes
linespace: 1.5
output:
  bookdown::pdf_document2:
    latex_engine: xelatex
    number_sections: yes
    keep_tex: yes
    fig_caption: yes
    toc: yes
    dev: cairo_pdf
    extra_dependencies: ["float"]
    template: "template/tex/plain.tex"
  # bookdown::word_document2:
  #   dev: png
params:
  preview: false
  appendix: true
---

```{r render, eval = FALSE, include = FALSE, echo = FALSE}
library(here)
rmarkdown::render(
  input = here("root-appendix.rmd"),
  output_format = "all",
  output_file = "appendix",
  output_dir = "publish"
)

# direct complie via tinytex
# tinytex::xelatex("publish/RIETI/webRCT/webRCT.tex")
```

```{r include = FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  echo = FALSE,
  cache = FALSE,
  include = TRUE,
  fig.pos = "t",
  fig.width = 10,
  fig.height = 6
)

format <- knitr::opts_knit$get("rmarkdown.pandoc.to")
out <- switch(format,
  "latex" = "kableExtra",
  "docx" = "flextable"
)

library(RCTtoolbox)
options(
  knitr.kable.NA = " ",
  knitr.table.format = "latex",
  modelsummary_stars_note = FALSE,
  modelsummary_format_numeric_latex = "plain",
  RCTtoolbox.table_output = out,
  RCTtoolbox.table_fontsize = 9
)
```

\clearpage


# (APPENDIX) Appendix {-}

# Background on Routine Rubella Vaccination in Japan

```{r child = "md/3-background.rmd"}

```

\clearpage

# Additional Tables and Figures about Online Survey Experiment

```{r}
library(here)
knitr::spin_child(here("src", "2-summary-experiment.r"))
```

\clearpage

# Results of Balance Test

```{r}
library(here)
knitr::spin_child(here("src", "3-selection1-balance-test.r"))
```

\clearpage

# Estimation Results of Linear Probability Models

```{r}
library(here)
knitr::spin_child(here("src", "4-selection1-intention.r"))
knitr::spin_child(here("src", "5-selection1-behavior.r"))
```


\clearpage

# Analysis to Address Recall Bias Associated with Self-Reporting of Behavior

```{r}
library(here)
knitr::spin_child(here("src", "7-selection2-balance-test.r"))
knitr::spin_child(here("src", "8-selection2-behavior.r"))
knitr::spin_child(here("src", "9-selection2-money.r"))
```
