---
title: |
  Results: Framework
subtitle: Preview
author: Hiroki Kato
bibliography: ../MHLW Rubella Nudge.bib
output:
  bookdown::html_document2:
    toc: true
    toc_float: true
    number_sections: false
params:
  preview: true
  appendix: false
---

```{r eval = FALSE, include = FALSE, echo = FALSE}
library(here)
rmarkdown::render(
  input = here("md", "2-framework.rmd"),
  output_format = "all",
  output_dir = "report/view"
)
```

ナッジ・メッセージの政策対象は抗体検査やワクチン接種を受けていない男性である。
そこで、第1回調査時点で抗体検査とワクチン接種を受けていない回答者に限定して、
ナッジ・メッセージの効果を推定する。
意向に関するアウトカム変数に対する効果を推定するとき、
第1回調査で過去に抗体検査を受検した、もしくはワクチンを接種したと回答した人を
除いたデータを用いる（以降、wave 1 target dataと呼ぶ）。
また、行動に関するアウトカム変数に対する効果を推定するとき、
上述の基準に加えて、
第2回調査で第1回調査以前に抗体検査を受検したもしくはワクチンを接種したと回答した人を
除いたデータを用いる（以降、wave 2 target dataと呼ぶ）[^second-criterion]。

[^second-criterion]: 第1回調査以降に自身の接種歴を調べ直すなどによって、
第1回調査と第2回調査の回答に違いが生じる可能性がある。
そのため、どちらかの調査で第1回調査以前に抗体検査を受検したもしくはワクチンを接種したと回答した人を除いた。

さらに、我々の目的は、金銭的インセンティブを取得した状況と
追加的な取引費用を支払わないとインセンティブが取得できない状況のそれぞれで、
ナッジ・メッセージの効果を推定することである。
そのために、上記の基準で構築したデータを
2019年度にクーポン券が自動的に送付されるかどうかで分割して、
それぞれのサブサンプルにおけるナッジ・メッセージの効果を推定する。
我々は2019年度にクーポン券が自動的に送付されるかどうかを2019年4月時点の年齢で識別した。
各市区町村は2019年度に40歳以上46歳以下の男性のクーポン券を送付し、
2020年度以降に47歳以上56歳以下の男性のクーポン券を送付する。
ただし、市区町村の判断や本人の希望に応じて、
47歳以上56歳以下の男性もクーポン券を受け取ることはできるが、
これは我々の分析に大きな影響を与えないと考えている。
なぜなら、2019年度に47歳以上の男性にクーポン券を送付する自治体は少ないからである。
また、我々のサーベイより、47歳以上の男性の約77%がクーポン券制度を認知していなかった。
仮に彼らがクーポン券制度を知っていたとしても、クーポン券を発行してもらうように依頼する必要がある。
以上の2点の理由から、47歳以上の男性がクーポン券の取得を望んでいるとは考えにくい。